<?php

echo <<<FORM
    <form action="changeAvatar" method="post" enctype="multipart/form-data">
    Bild auswählen:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
    </form>    
FORM;


if (isset($_POST["submit"])) {
    $target_dir = "./images/";
    $target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]);
    $uploadOk = 1;
    $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
    $check = getimagesize($_FILES["fileToUpload"]["tmp_name"]);
    if ($check !== false) {
        echo "Datei ist ein Bild - " . $check["mime"] . ".";
        $uploadOk = 1;
    } else {
        echo "File is not an image.";
        $uploadOk = 0;
    }

// Check if file already exists
    if (file_exists($target_file)) {
        echo "Sorry, file already exists.";
        $uploadOk = 0;
    }
// Check file size
    if ($_FILES["fileToUpload"]["size"] > 500000) {
        echo "Ihr Bild ist leider zu gross. Bitte verkleinern Sie es und versuchen es nochmals.";
        $uploadOk = 0;
    }
// Allow certain file formats
    if ($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg" && $imageFileType != "gif") {
        echo "Sorry, only JPG, JPEG, PNG & GIF files are allowed.";
        $uploadOk = 0;
    }
// Check if $uploadOk is set to 0 by an error
    if ($uploadOk == 0) {
        echo "Sorry, your file was not uploaded.";
// if everything is ok, try to upload file
    } else {
        
                mt_srand((double) microtime() * 1000000);
        $set = "ABCDEFGHIKLMNPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz123456789";
        $randomvalue = "";

        for ($i = 1; $i <= 10; $i++) {
            $randomvalue .= $set[mt_rand(0, (strlen($set) - 1))];
        }
        
        $logopath ="./public/img/users/";
        
        if (move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $logopath  . $randomvalue . "." . $imageFileType)) {
            echo "Das Bild " . basename($_FILES["fileToUpload"]["name"]) . " wurde hochgeladen.<br>";
            echo "<a href=''>...zum Userbereich<a>";
            
            $user = $em->find('Backend\Entity\User', $this->zfcUserIdentity()->getId());
            $oldlogo = $user->getLogo();
            $user->setLogo($randomvalue . "." . $imageFileType);
            $em->flush();
            unlink($logopath . $oldlogo);
        } else {
            echo "Ups, Ihr Bild konnte nicht hochgeladen werden!";
        }
    }
}