<?php

echo <<<FORM
    <form action="changeAvatar" method="post" enctype="multipart/form-data">
        <p><img src="../img/avatarupload.png" alt="Logo"></p> 
        <strong><p>Bild auswählen:</p></strong>
        <input type="file" name="fileToUpload" id="fileToUpload">
        <br>
        <input type="submit" value="Bild hochladen" name="submit" class="btn btn-info">
    </form>   
FORM;


if (isset($_POST["submit"])) {
    $target_dir = "./images/";
    $target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]);
    $uploadOk = 1;
    $imageFileType = pathinfo($target_file, PATHINFO_EXTENSION);
    $check = getimagesize($_FILES["fileToUpload"]["tmp_name"]);
    if ($check !== false) {
        $uploadOk = 1;
    } else {
        echo "File is not an image.";
        $uploadOk = 0;
    }

    //Überprüfen ob File bereits vorhanden - eher unwahrscheinlich
    if (file_exists($target_file)) {
        echo "Bitte versuchen Sie es noch einmal.";
        $uploadOk = 0;
    }
// Filegrösse überprüfen
    if ($_FILES["fileToUpload"]["size"] > 1000000) {
        echo "<p>Ihr Bild ist leider zu gross. Bitte verkleinern Sie es und versuchen es nochmals.<p><br>";
        echo "<p>Maximal 1 MB.<p><br>";
        $uploadOk = 0;
    }
// Auf Format prüfen
    if ($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg" && $imageFileType != "gif") {
        echo "Sorry, nur JPG, JPEG, PNG & GIF Dateien sind erlaubt.";
        $uploadOk = 0;
    }
// Wurden alle Bedingungen erfüllt
    if ($uploadOk == 0) {
        echo "Sorry, Ihr Bild wurde nicht hochgeladen.";
    } else {

        mt_srand((double) microtime() * 1000000);
        $set = "ABCDEFGHIKLMNPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz123456789";
        $randomvalue = "";

        for ($i = 1; $i <= 10; $i++) {
            $randomvalue .= $set[mt_rand(0, (strlen($set) - 1))];
        }

        $logopath = "./public/img/users/";

        //Versuchen Hochzuladen.
        if (move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $logopath . $randomvalue . "." . $imageFileType)) {
            echo "Das Bild " . basename($_FILES["fileToUpload"]["name"]) . " wurde hochgeladen.<br>";
            echo "<a href='/Backend'>...zum Userbereich<a>";

            //Filename bei User hinterlegen
            $user = $em->find('Backend\Entity\User', $this->zfcUserIdentity()->getId());
            $oldlogo = $user->getLogo();
            $user->setLogo($randomvalue . "." . $imageFileType);
            $em->flush();

            //allfälliges altes Logo löschen
            if (!empty($oldlogo)) {
                unlink($logopath . $oldlogo);
            }
        } else {
            echo "Ups, Ihr Bild konnte nicht hochgeladen werden!";
        }
    }
}