<?php

include_once 'adminView.php';
include_once 'userView.php';
include_once 'editUserView.php';

if (!empty($_POST['editUser'])) {  //mit switch-case lösen!!!!!
       
    if ($_POST['editUser'] == "A") {
        echo'<meta http-equiv="refresh" content="0; url=../Backend/changeAvatar" />';
    }
    elseif ($_POST['editUser'] == "D") {
        echo'<meta http-equiv="refresh" content="0; url=../Backend/deactivateUser" />';
    }
    elseif ($_POST['editUser'] == "E") {
        echo'<meta http-equiv="refresh" content="0; url=../user/change-email" />';
    }
    elseif ($_POST['editUser'] == "P") {
        echo'<meta http-equiv="refresh" content="0; url=../user/change-password" />';
    } else {
        $view = new editUserView();
        if ($this->isAllowed('user', 'administrateAll')) {
            $view->setAdmin();
            $view->editUser($em, $_POST['editUser']);
        } else {
            $view->editUser($em, $this->zfcUserIdentity()->getId());
        }
    }
} elseif (!empty($_POST['changeUser']) && $_POST['changeUser'] == 'UsErChAnGe') {
    $user = $em->find('Backend\Entity\User',$_POST['userID']);
    $user->setContactLast($_POST['contactLast']);
    $user->setContactSur($_POST['contactSur']);
    $user->setOrgname($_POST['orgname']);
    $user->setStreet($_POST['street']);
    $user->setStreetNr($_POST['streetNr']);
    $user->setZip($_POST['zip']);
    $user->setCity($_POST['city']);
    $user->setPhone($_POST['phone']);
        if(!empty($_POST['password'])){
            include_once('vendor\zendframework\zendframework\library\Zend\Crypt\Password\bcrypt.php'); 
            $bcrypt = new Zend\Crypt\Password\Bcrypt();
            $bcrypt->setCost(14);
            $user->setPassword( $bcrypt->create($_POST['password']));
}    
    $em->flush();
    echo "Daten wurden erfolgreich geändert. Bitte begeben Sie sich wieder in den Userbereich und überprüfen sie die Angaben";
} elseif(!empty($_POST['changeAvatar']) && $_POST['changeAvatar'] == 'A'){
    
}
else {

    if ($this->isAllowed('user', 'administrateAll')) {
        $view = new adminView($em);
        $view->display();
    } elseif ($this->isAllowed('user', 'administrateOwn')) {
        if ($this->zfcUserIdentity()->getState() == 1) {
            $view = new userView($em, $this->zfcUserIdentity());
            $view->display();
        } else {
            echo "<h1>Nur noch einen Schritt!</h1><br>";
            echo "<p>Um den Userbereich zu Nutzen, müssen Sie Ihre E-Mail Adresse bestätigen.</p><br>";
            echo "<p>Sie sollten in den nächsten Minuten eine E-Mail von uns erhalten.";
            //->button für neu Senden von Mail
        }
    } else {
        echo'<meta http-equiv="refresh" content="0; url=../user/login" />';
    }
}