<?php

$verbindung = mysql_connect("localhost", "badenfahrer", "1234")
        or die("keine Verbindung möglich Benutzername oder Passwort sind falsch");

mysql_select_db("db_badenfahrt")
        or die("Die Datenbank existiert nicht.");

if (!empty($_GET['id']) AND ! empty($_GET['code'])) {

    $id = $_GET['id'];

    $abfrage = "SELECT email FROM user WHERE id LIKE " . $id;
    $ergebnis = mysql_query($abfrage);


    echo $ergebnis;
    mysql_close($verbindung);

//    $view = new editUserView($em);
//    echo $user->getEmail();
} else {

    echo '<meta http-equiv = "refresh" content = "0; url=../" />';
}



//          'host'     => 'localhost',
//          'port'     => '3306',
//          'user'     => 'badenfahrer',
//          'password' => '1234',
//          'dbname'   => 'db_badenfahrt',
?>



