<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Badenfahrt 2017') ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Stadt Baden"/>&nbsp;<?php echo 'Badenfahrt 2017' ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo 'Home' ?></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Info <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('actual') ?>"><?php echo 'Aktuelle Badenfahrt' ?></a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('general') ?>"><?php echo 'Generelles über die Badenfahrt' ?></a></li>
                                <li><a href="<?php echo $this->url('history') ?>"><?php echo 'Geschichte Badenfahrt' ?></a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('location') ?>"><?php echo 'Informationen Stand' ?></a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class=" btn btn-xs btn-success"><a href="<?php echo $this->url('Backend') ?>"><?php echo 'TEST' ?></a></li>
                        <li class="btn btn-xs btn-default"><a href="<?php  echo $this->url('login') ?>"><?php echo 'Login' ?></a></li> 
                        <li class="btn btn-xs btn-default"><a href="<?php  echo $this->url('register') ?>"><?php echo 'Registrieren' ?></a></li> 
                        
                    </ul> <!--  -->
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <!--        <div class="banner">
                    <img src="<?php echo $this->basePath('img/banner.png') ?>" class ="img-responsive center-block" alt="Banner"/>
                </div>-->
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2015 - <?php echo date('Y') ?> by Gruppe JKI <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
