<div class="jumbotron">
    <h1>Das Fest</h1>
    <br>
    <p>Das Festgelände erstreckt sich über die gesamte Altstadt und umfasst auch Bereiche um den Bahnhof. Ein wesentlicher Bestandteil sind die 
        etwa 110 "Festbeizen": Restaurants, Bars und andere Attraktionen, die grösstenteils von Vereinen aus der Region organisiert und betrieben 
        werden. Dabei handelt es sich nicht um gewöhnliche Bierzelte sondern um individuelle Kreationen, in die viel Fantasie aber oft auch das 
        Können von Architekten, Bauingenieuren und Handwerkern unter den Vereinsmitgliedern investiert wird. So wurden für "Welt statt Baden" 2007 
        unter anderem ein Moulin Rouge, ein French Quarter, ein griechischer Tempel, ein Bambustempel, ein Sing Sing und eine Klosterwirtschaft errichtet.

        Daneben gibt es zahlreiche kulturelle Veranstaltungen, wie z.B. Theateraufführungen oder Openair-Konzerte mit bekannten Bands und Musikern. 
        Höhepunkte des Festes sind die an den beiden Festsonntagen durchgeführten Umzüge, bei denen sich alle an der Badenfahrt beteiligten Vereine 
        präsentieren, sowie das Feuerwerk über der Ruine Stein.

        Während der Badenfahrt gibt es traditionell in den Badener Bäckereien die Spanisch Brötli.</p>
</div>

<div class="jumbotron">
    <h1>Organisation</h1>
    <br>
    <p>Die Badenfahrt wird von einem privaten Verein, dem «Badenfahrt-Komitee» organisiert. Personell ist diese stark mit der lokalen 
        Badener Politik und öffentlichen Leistungserbringern besetzt. Dieses übergeordnete Komitee bestimmt die groben Strukturen des Festes, 
        wie Motto, Umzug, Feuerwerk, Infrastruktur, Öffnungszeiten, öffentliche Veranstaltungen etc. Im Bereich Infrastruktur werden wichtige 
        und zentrale Dienstleistungen organisiert und zentral in Auftrag gegeben. Dazu gehören insbesondere Abfallbewirtschaftung, Strom- und 
        Wasserversorgung, Platzzuteilung, Regelung des Auf- und Abbaus.

        Die eigentlichen Festbeizen, welche von Vereinen und teilweise von Gemeinden oder Firmen betrieben werden, sind nochmals selbständig mit je 
        einem eigenen OK organisiert. Die Rahmenbedingungen, welche vom Komitee vorgegeben werden, lassen viel Spielraum. Somit bleibt es jedem 
        Veranstalter selber überlassen ein Budget auszuarbeiten, ein Konzept für den Betrieb aufzustellen, Bauten zu planen und umzusetzen, Helfer zu 
        organisieren etc.</p>
</div>