<div class="jumbotron">
    <h1>Historischer Hintergrund</h1>
    <br>
    <p>Der Begriff «Badenfahrt» wurde im Mittelalter geprägt, als das Städtchen Baden wegen seiner heissen Thermalquellen und der 
        damit verbundenen Zerstreuungen ein beliebtes Reiseziel für weltliche und geistliche Würdenträger war. Insbesondere der Status 
        Badens als wichtigster Sitzungsort der eidgenössischen Tagsatzung trug dazu bei. Nach der Reformation begaben sich auch viele 
        Bürger Zürichs ins katholisch gebliebene Baden, um sich zeitweise den strengen zwinglianischen Sittenvorschriften zu entziehen. 
        In besseren Kreisen war es durchaus üblich nach Baden in eine Kur zu fahren und sich dabei auf dem Heiratsmarkt umzusehen, bzw. 
        zu zeigen. Schriftsteller wie David Hess, Niklaus Manuel und Thomas Murner nahmen auf Badenfahrten Bezug. Die «Spanisch-Brötli-Bahn», 
        die erste Eisenbahn auf Schweizer Boden, förderte ab 1847 den Badetourismus zusätzlich.

        Das erste Volksfest mit der Bezeichnung Badenfahrt fand 1923 statt und gedachte des Friedenskongresses von 1714, an dem europäische 
        Gesandte den Frieden von Baden ausgehandelt hatten, der zur Beendigung des Spanischen Erbfolgekrieges beitrug. Die erste «grosse» 
        Badenfahrt wurde 1937 durchgeführt. Das Fest von 1947 stand unter dem Zeichen der Hundertjahrfeier der Schweizer Eisenbahnen, wobei 
        die SBB Baden als offiziellen Festort bestimmte. Das für 1957 geplante Fest fiel wegen der umfassenden Verkehrssanierung aus. Die 
        Tradition wurde aber 1967 wieder fortgeführt. 1972 bzw. 1982 fanden sogenannte «kleine» Badenfahrten statt, welche seither aber nicht 
        mehr durchgeführt wurden.</p>
</div>

<div class="jumbotron">
    <h1>Chronologie</h1>
    <br>
    <p>
    <table class="table">
        <thead>
            <tr>
                <td>Jahr</td>
                <td>Motto</td>
                <td>Bemerkung</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1923</td>
                <td>unbekannt</td>
                <td>Um Geld für die Theaterstiftung aufzutreiben, wurde ein Fundraising betrieben</td>
            </tr>
            <tr>
                <td>1937</td>
                <td>«Im Wandel der Zeiten»</td>
                <td>Zum 90. Jubiläum der Spanisch-Brötli-Bahn liessen die «Badenfahrer» die Biedermeierzeit wieder aufleben</td>
            </tr>
            <tr>
                <td>1947</td>
                <td>unbekannt</td>
                <td>Auch zum 100-jährigen Bestehen wurden die Festbesucher mit nostalgischen Kostümen in die glorreichen Zeiten der Stadt Baden zurückversetzt</td>
            </tr>
            <tr>
                <td>1957</td>
                <td></td>
                <td>Die Badenfahrt entfiel wegen grösserer Umbauarbeiten, insbesondere im Bereich der Schulhausplatz-Kreuzung und des Bahnhofs</td>
            </tr>
            <tr>
                <td>1967</td>
                <td>«Räder machen Leute»</td>
                <td>Integration und Gemeinschaftsförderung sollten durch das Fest gefördert werden</td>
            </tr>
            <tr>
                <td>1972</td>
                <td>«125 Jahre Spanisch-Brötli-Bahn»</td>
                <td>Da das Jubiläum aus dem Zehnjahres-Intervall fiel, wurde dieses Fest als «kleine» Badenfahrt bezeichnet</td>
            </tr>
            <tr>
                <td>1977</td>
                <td>«Wasser»</td>
                <td></td>
            </tr>
            <tr>
                <td>1982</td>
                <td>«Illusionen»</td>
                <td></td>
            </tr>
            <tr>
                <td>1987</td>
                <td>«Bade fahrt ab»</td>
                <td></td>
            </tr>
            <tr>
                <td>1997</td>
                <td>«La Badenfahrt»</td>
                <td></td>
            </tr>
            <tr>
                <td>2007</td>
                <td>«Welt statt Baden»</td>
                <td>Die fünf Festbezirke hatten nochmals ihre jeweiligen Untermottos: «Alte Welt / Neue Welt», «Götterwelten / Mythologien», 
                    «Unterwelt / Halbwelt», «Glamour- und Glitzerwelt, Spielwelten», «Wasserwelt / Inselwelten / Südseeträume»</td>
            </tr>
            <tr>
                <td>2012</td>
                <td>«Geschichte schichten»</td>
                <td>Das Stadtfest 2012 erinnert an die Schleifung von Schloss Stein nach der Kapitulation Badens im Zweiten Villmergerkrieg 
                    und wird auch als «kleine» Badenfahrt bezeichnet</td>
            </tr>
        </tbody>
    </table>
</p>
</div>
