<div class="page-header">
    <h1>Willkommen auf der Webseite der Badenfahrt 2017
        <br>
        <small>Hier finden Sie alle nötigen Infos </small>
        <br>
        <img src="<?php echo $this->basePath('img/bft.png') ?>" class ="img-responsive center-block" alt="Bild Badenfahrt"/>
    </h1>
</div>

<div class="jumbotron">
    <p>Die Badenfahrt ist ein mehrtägiges Volksfest in Baden in der Schweiz. Sie wird in der Regel nur alle zehn Jahre organisiert, ist 
        aber mit jeweils bis zu einer Million Besuchern eines der grössten Feste der Schweiz und das mit Abstand grösste im Kanton Aargau. Die elfte 
        Ausgabe der Badenfahrt fand vom Freitag, 17. August bis Sonntag, 26. August 2007 während zehn Tagen statt und stand unter dem Motto «Welt statt Baden». 
        Bisweilen findet fünf Jahre vor bzw. nach einer Badenfahrt ein Stadtfest statt, das im Volksmund «kleine Badenfahrt» genannt wird. So fand auch im Jahre 2012 
        vom 17. bis zum 26. August ein Stadtfest unter dem Motto «Geschichte schichten» statt, das auch an die Zerstörung von Schloss Stein 300 Jahre vorher erinnert.
    </p>
</div>