<!-- Indexseite -->

<!-- Container mit Seitenüberschrift und Bild -->
<div class="page-header">
    <div class="col-md-12 column col-md-offset-1">
    <h1>Willkommen auf der Webseite der Badenfahrt 2017
        <br>
        <small>Hier finden Sie alle nötigen Infos </small>
        <br>
<!--        <img src="<?php echo $this->basePath('img/bft.png') ?>" class ="img-responsive center-block" alt="Bild Badenfahrt"/>-->
        </h1>
</div>
        
        
        
        
        <div class="col-md-10 column col-md-offset-1">
			<div class="carousel slide" id="carousel-328376"  data-interval="false">
				<ol class="carousel-indicators">
					<li data-slide-to="0" data-target="#carousel-328376" class="active">
					</li>
					<li data-slide-to="1" data-target="#carousel-328376">
					</li>
					<li data-slide-to="2" data-target="#carousel-328376">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="item active">
						<img src="img/banner.png" >
						<div class="carousel-caption">
							<h4>
								First Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
					<div class="item">
						<img alt="" src="img/Baden_Stein.png" />
						<div class="carousel-caption">
							<h4>
								Titel 2
							</h4>
							<p>
								Test-text
							</p>
						</div>
					</div>
					<div class="item">
						<img alt="" src="http://placehold.it/1200x450" />
						<div class="carousel-caption">
							<h4>
								Titel 3
							</h4>
							<p> Test-text
						
							</p>
						</div>
					</div>
				</div> <a class="left carousel-control" href="#carousel-328376" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-328376" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
    
<!-- Ende Container -->

<!-- Container mit generellen Infos über die Badenfahrt -->
<div class="jumbotron">
    <p class="text-info">Die Badenfahrt ist ein mehrtägiges Volksfest in Baden in der Schweiz. Sie wird in der Regel nur alle zehn Jahre organisiert, ist 
        aber mit jeweils bis zu einer Million Besuchern eines der grössten Feste der Schweiz und das mit Abstand grösste im Kanton Aargau. Die elfte 
        Ausgabe der Badenfahrt fand vom Freitag, 17. August bis Sonntag, 26. August 2007 während zehn Tagen statt und stand unter dem Motto «Welt statt Baden». 
        Bisweilen findet fünf Jahre vor bzw. nach einer Badenfahrt ein Stadtfest statt, das im Volksmund «kleine Badenfahrt» genannt wird. So fand auch im Jahre 2012 
        vom 17. bis zum 26. August ein Stadtfest unter dem Motto «Geschichte schichten» statt, das auch an die Zerstörung von Schloss Stein 300 Jahre vorher erinnert.
    </p>
</div>   
<!-- Ende Container -->