<?php

if(!empty($_POST['sendMail'])){
    echo "<div class='alert alert-success' role='alert'>Passwort-Rücsetzungsmail (geile Name) wurde an Ihre E-Mail Adresse gesendet.</div>";  

    $user = $em->getRepository('Backend\Entity\User')->findOneBy(
        array('email' => $_POST['email']));
    
    if(!empty($user)){
        $user->set
        echo $user->getContactSur();    
    }

}

else{
echo <<<FORM
<form class="form-horizontal" method="post">
<div class="form-group">
            <label class="col-lg-3 control-label">E-Mail Adresse:</label>
            <div class="col-lg-8">
              <input name="email" class="form-control" type="email" placeholder="Ihre E-Mail Adresse" required=true>
            </div>
</div>



<button class='btn-lg btn-success' type='submit' name='sendMail' value="sendMail" ><i class='glyphicon glyphicon-envelope'></i> Mail blabla</button>
</form>


FORM;




}


//$userRepository = $em->getRepository('Backend\Entity\User');
//$users = $userRepository->findAll();
//
// foreach ($users as $user) {
//     echo $user->getDoubleoptin();
// }