<?php

//filter_input(INPUT_POST, 'var_name')


if(!empty($_POST['sendMail'])){
    echo "<div class='alert alert-success' role='alert'>Passwort-Rücksetzungsmail (geile Name) wurde an Ihre E-Mail Adresse gesendet.</div>";  

    //User anhand E-Mail Adresse suchen
    $user = $em->getRepository('Backend\Entity\User')->findOneBy(
        array('email' => $_POST['email']));
    
    //Sofern E-Mail Adresse in DB vorhanden
    if(!empty($user)){
        if($user->getState()<9){            //nur wenn User nicht gesperrt ist! Also untererhalb Status 9
            $user->setForgotpwtoken(20);    //neuen Passwort-Vergessen-Token erstellen (Anzahl Zeichen)
            $em->flush();                   //erstellten Token speichern
            $user->sendForgotPasswordMail(); 
        }
    }

}

else{
echo <<<FORM
<form class="form-horizontal" method="post">
<div class="form-group">
            <label class="col-lg-3 control-label">E-Mail Adresse:</label>
            <div class="col-lg-8">
              <input name="email" class="form-control" type="email" placeholder="Ihre E-Mail Adresse" required=true>
            </div>
</div>



<button class='btn-lg btn-success' type='submit' name='sendMail' value="sendMail" ><i class='glyphicon glyphicon-envelope'></i> Mail blabla</button>
</form>


FORM;




}
