<?php

//Eingabeformular
$FORM = '<form class="form-horizontal" method="post">
<div class="form-group">
            <label class="col-lg-3 control-label">Neues Passwort:</label>
            <div class="col-lg-8">
              <input name="password" class="form-control" type="password" placeholder="Ihr neues Passwort" required>
            </div>
                <label class="col-lg-3 control-label">Neues Passwort wiederholen:</label>
            <div class="col-lg-8">
              <input name="passwordverify" class="form-control" type="password" placeholder="Ihr neues Passwort wiederholen" required>
            </div>
</div>

<button class="btn-lg btn-success" type="submit" name="resetPassword" value="resetPassword" ><i class="glyphicon glyphicon-envelope"></i> Speichern</button>
</form>';
//------------------------------------

if($_SERVER['REQUEST_METHOD']=="GET"){
$pwtoken = $_GET["pwtoken"];

$user = $em->getRepository('Backend\Entity\User')->findOneBy(
        array('forgotpwtoken' => $pwtoken));
if (isset($user)) {
       
echo $FORM;
    
    
}
else {
    echo "<div class='alert alert-warning' role='alert'>Dieses Rücksetzungsmail ist ungültig oder bereits verwendet!</div>";
}
}

//Beim Absenden des Formulars
if($_SERVER['REQUEST_METHOD']=="POST"){
    if($_POST["password"]==$_POST["passwordverify"]){   //Passwörter stimmen überein
        if(strlen($_POST["password"])>=6){              //Passwort minimum 6 Stellen
           $pwtoken = $_GET["pwtoken"];                 
           $user = $em->getRepository('Backend\Entity\User')->findOneBy(  //User anhand Passwort-Token suchen
            array('forgotpwtoken' => $pwtoken));
            if (isset($user)) {
             include_once('vendor\zendframework\zendframework\library\Zend\Crypt\Password\bcrypt.php'); 
           $bcrypt = new Zend\Crypt\Password\Bcrypt();
           $bcrypt->setCost(14);
           $user->setPassword( $bcrypt->create($_POST['password']));  //neuen Passwort-Hash erstellen
           $user->setForgotpwtoken(0);  //neuen Hash speichern
           $em->flush();   
            }

        }
        else{
            echo "<div class='alert alert-warning' role='alert'>Das Passwort muss mindestens 6 Stellen haben.</div>";
        }
        
    }
    else{ //Passwörter stimmen nicht überein
    echo "<div class='alert alert-warning' role='alert'>Die beiden Passwörter stimmen nicht überein!</div>";
    echo $FORM;
    }
    
    
}